### ISSUE TITLE
Invalid format on erase

### ISSUE THREAD

**Issue by Nico04** [caseyryan/flutter_multi_formatter#1]
Using `MoneyInputFormatter`, if you remove a character with backspace key, it result easily to an invalid format input.

For instance with _1 235€_, if I backspace on the _3_, it shows _1 25€_.

**Comment by caseyryan** [comment]
I know about this, but it's an indended behavior to avoid endless recursion. When I have time, I'll try to change this

**Comment by Nico04** [comment]
Strange way to handle an issue.
I'll hope you'll find time for this some day, thanks.

**Comment by caseyryan** [comment]
> Strange way to handle an issue.

Why is it strange?

**Comment by Nico04** [comment]
> 
> 
> > Strange way to handle an issue.
> 
> Why is it strange?

We usually close an issue only when it's resolved, fixed or implemented, not before ;)

**Comment by caseyryan** [comment]
> > > Strange way to handle an issue.
> > 
> > 
> > Why is it strange?
> 
> We usually close an issue only when it's resolved, fixed or implemented, not before ;)
I agree, I must have clicked the wrong button. 
Anyway, I can't promise to resolve it very quickly because I'm very busy. If you can fix it yourself and you need it fixed, feel free to create a pull request ;-)

**Comment by caseyryan** [comment]
This bug is fixed locally and I will update the package this weekend
