### ISSUE TITLE
Expose `_formatByMask`

### ISSUE THREAD

**Issue by RodolfoSilva** [caseyryan/flutter_multi_formatter#101]
Could we expose the method from phone formatter `_formatByMask` as `formatPhoneByMask`. This will help when we need to format an unmasked number from the server.

https://github.com/caseyryan/flutter_multi_formatter/blob/master/lib/formatters/phone_input_formatter.dart#L175-L181

**Comment by caseyryan** [comment]
There is already a global method called formatAsPhoneNumber() won't it fit your goal?

**Comment by RodolfoSilva** [comment]
Sorry, thanks!
