### ISSUE TITLE
print('RETURN 0 ${oldValue.text}');

### ISSUE THREAD

**Issue by Aljnk** [caseyryan/flutter_multi_formatter#102]
You forgot to remove "print" in new version. 
![Screenshot_2](https://user-images.githubusercontent.com/11256478/197487183-47aeb1b1-aa56-4de1-a2d2-b9a54b4e2093.jpg)

Too mutch texts in console :)
![Screenshot_1](https://user-images.githubusercontent.com/11256478/197487179-661f8d4b-10d7-43b1-be71-ad57bf08a765.jpg)

**Comment by caseyryan** [comment]
Hi! Thanks, I'll remove them

**Comment by caseyryan** [comment]
Removed in 2.8.5
