### ISSUE TITLE
Bug in Pakistan Phone Number Formatter.

### ISSUE THREAD

**Issue by OsamaQureshi796** [caseyryan/flutter_multi_formatter#103]
Hi.
Thanks for having such an amazing plugin.

I've come up with an issue is that when i select Pakistan for number formatting there i see the incorrect format while for other countries phone number it's working well.

Let me explain:
Valid Phone Number: Country Code and then 10 digits
for example: +92 331 1234567

So when i select Pakistan then the formatter only allow 7 digits instead of 10 .
For example: +92 331 1234 so the last 3 numbers is not in the plugin.

Kindly update it.
Thanks
Osama Qureshi

**Comment by caseyryan** [comment]
Hi! Thanks!
Fixed in 2.8.7
