### ISSUE TITLE
+06 Hungary (Alternative) and extra [U+200E] blank character in phoneMask of +681 Wallis and Futuna

### ISSUE THREAD

**Issue by patachi** [caseyryan/flutter_multi_formatter#104]
The national trunk code 06 used inside Hungary shall not be dialed from abroad. so it's better to get removed.
[phone_input_formatter.dart#L1219](https://github.com/caseyryan/flutter_multi_formatter/blob/master/lib/formatters/phone_input_formatter.dart#L1219)

There is an extra [U+200E] blank character at the beginning of `phoneMask` filed value.
[phone_input_formatter.dart#L1875](https://github.com/caseyryan/flutter_multi_formatter/blob/master/lib/formatters/phone_input_formatter.dart#L1875)

![image](https://user-images.githubusercontent.com/25434064/199939818-1f8b6890-e1f8-4eae-8a43-cfaae2cda813.png)

p.s: Thanks for this great package.

**Comment by caseyryan** [comment]
Hi! Thanks! Fixed this extra space. 
About Hungary, maybe you're right and it's better to be removed. But I believe it was added by one of pull requests, I think somebody might use it. So I decided to leave it for now, as an exception
