### ISSUE TITLE
toCurrencyString not working properly

### ISSUE THREAD

**Issue by igor00krnic** [caseyryan/flutter_multi_formatter#105]
toCurrencyString seems to be not working properly in version 2.9.5.

`
double tmpDouble = 2.02;

String tmpDoubleFormatted = tmpDouble.toCurrencyString(
        thousandSeparator: ThousandSeparator.Period,
        mantissaLength: 2,
      );

`

The value of tmpDoubleFormatted should be '2,02' but is '202,00'.

**Comment by caseyryan** [comment]
Thanks. Fixed in 2.9.6
