### ISSUE TITLE
CurrencyInputFormatter automatically appends zeros

### ISSUE THREAD

**Issue by banderberg** [caseyryan/flutter_multi_formatter#107]
Upgraded from MoneyInputFormatter to CurrencyInput formatter, and discovered this issue:

When the user enters a value into a field using CurrencyInputFormatter, the field automatically adds the decimal place and two zeros.  Further input by the user does not change the field.

Example:  User wants to enter in 3.45.  When they enter "3" the field changes to 3.00, and when they enter 4, nothing changes.  They have to select into the string after the decimal place to enter in values.

Using version 2.9.11

**Comment by banderberg** [comment]
`import 'package:flutter/material.dart';
import 'package:flutter_multi_formatter/formatters/currency_input_formatter.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextFormField(
              textCapitalization: TextCapitalization.none,
              autovalidateMode: AutovalidateMode.onUserInteraction,
              decoration: InputDecoration(
                alignLabelWithHint: false,
                disabledBorder: InputBorder.none,
                errorMaxLines: 2,
                hintStyle: Theme.of(context).textTheme.caption,
              ),
              inputFormatters: [CurrencyInputFormatter()],
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
`

**Comment by banderberg** [comment]
Running on sdk gphone64 x86 64

**Comment by banderberg** [comment]
To reitterate, using the code above, I enter 3, and immediately it updates the control to 3.00 and I cannot enter more digits unless I backspace or manually select into the value.  Setting mantissa 0 just makes it 3 with nothing after and I still cannot enter values.

**Comment by banderberg** [comment]
@caseyryan what do you think?

**Comment by caseyryan** [comment]
I think it's a problem of Flutter itself. They add some bugs periodically and then fix them. I couldn't reproduce this

**Comment by banderberg** [comment]
Would you mind showing me how yours behaves, or describing it?  And please
leave this issue open I would like to know if others are having this
issue.  I suspect some are due to the reacts.

**Comment by caseyryan** [comment]
I've finally found time to test it today. It was not a problem of Flutter but a problem of one of my other changes. Kinda side effect.
