### ISSUE TITLE
is there a possibility to add a new type of card to CreditSystem ? 

### ISSUE THREAD

**Issue by Caypoh23** [caseyryan/flutter_multi_formatter#109]

**Comment by caseyryan** [comment]
No. They use hardcoded constants.
Why do you need a new card system? Is it some custom or existing one?

**Comment by Caypoh23** [comment]
@caseyryan It is existing one

**Comment by caseyryan** [comment]
> @caseyryan It is existing one

So, what's you proposition?

**Comment by Caypoh23** [comment]
A possibility to add alternative card system as in phone input formatter (method addAlternativePhoneMasks). User can enter     
```
{
      'system': 'UzCard',
      'systemCode': '8600',
      'numberMask': '0000 0000 0000 0000',
      'numDigits': 16,
},
```

> > @caseyryan It is existing one
> 
> So, what's you proposition?

**Comment by caseyryan** [comment]
added in Added in 2.11.5
