### ISSUE TITLE
Disable negative sign for MoneyInputFormatter

### ISSUE THREAD

**Issue by awhitford** [caseyryan/flutter_multi_formatter#11]
I often need to avoid the risk of a negative money amount.  For example:
 * an Item Price can't be negative, or
 * a Tip can't be negative.

As a result, it would be great if we could have the option to disable the negative sign to prevent input of a negative money amount.

**Comment by awhitford** [comment]
Actually, I just realized that I just need to add this:
```dart
BlacklistingTextInputFormatter('-'),
```

**Comment by ericbenwa** [comment]
How should this be handled if `BlacklistingTextInputFormatter` has been deprecated?
I'm using `MoneyInputFormatter` and don't want a person to type a minus ("-") into the textfield.
