### ISSUE TITLE
wrong cursor

### ISSUE THREAD

**Issue by jackie-maxx** [caseyryan/flutter_multi_formatter#110]
my code

TextFormField(
              inputFormatters: [
                CurrencyInputFormatter(
                  thousandSeparator: ThousandSeparator.Comma,
                  mantissaLength: 2,
                ),
              ],
              keyboardType: const TextInputType.numberWithOptions(decimal: true, signed: false),
            ),

1. When i input first number into the textFormField the cursor it move to the last like below picture
![Simulator Screen Shot - iPhone 13 - 2022-12-17 at 09 56 33](https://user-images.githubusercontent.com/104404240/208220964-2bbad34b-e6e6-4cbb-b434-20aa94cbaad6.png)

2. When i delete all and input again it show zero number above number i input like below picture 
![Simulator Screen Shot - iPhone 13 - 2022-12-17 at 09 56 55](https://user-images.githubusercontent.com/104404240/208220953-4a21020d-833d-491f-8f15-f3b4847a36ac.png)

3. I using Cambodia Region in IOS device it show  Comma "," in keyboard (type number) and When i select on it the cursor not move to the next of dot (".")  -> Example   i input 1,234.00  
![12345](https://user-images.githubusercontent.com/104404240/208221335-14681ea2-07ec-48f2-809a-add7f7a7a4b9.jpg)

**Comment by caseyryan** [comment]
Fixed in 2.9.14
