### ISSUE TITLE
[BUG] input value reset to 1 digit after inputting the 5th digits

### ISSUE THREAD

**Issue by kimmanwky** [caseyryan/flutter_multi_formatter#111]
```
CurrencyInputFormatter(
    mantissaLength: 0,
    thousandSeparator: ThousandSeparator.Comma,
 ),
```

I set mantissaLength to "0", it will give me error and input value reduce/reset to only 1 digit after inputting the 5th digit.

From >>
![image](https://user-images.githubusercontent.com/19542037/208843229-d172a8ff-8aef-4145-899b-ede1f03bdf38.png)

To >>
![image](https://user-images.githubusercontent.com/19542037/208843321-29860865-a7a0-42ff-8cda-a8b641e5d41a.png)

Error screenshot after inputting 5 digits (e.g. 11111):

![image](https://user-images.githubusercontent.com/19542037/208842879-1102c805-d3e6-4ee8-9ae3-97ab476dc0b9.png)

I have tried if I set mantissaLength to "1" or more, it works fine.
![image](https://user-images.githubusercontent.com/19542037/208843701-b2a9fea4-1ab5-49be-8d55-14de6a7bbe97.png)

**Comment by kimmanwky** [comment]
@caseyryan

**Comment by caseyryan** [comment]
I'll take a look at this as soon as I have time
