### ISSUE TITLE
`toCurrencyString` multiplies result by 10 when target decimal separator is comma

### ISSUE THREAD

**Issue by nizioleque** [caseyryan/flutter_multi_formatter#116]
Example code:
```dart
(1.0).toCurrencyString(
  thousandSeparator: ThousandSeparator.Period,
);
```
returns `"10,00"` instead of expected `"1,00"`.

The same happens with the following code:
```dart
toCurrencyString(
  (1.0).toString(),
  thousandSeparator: ThousandSeparator.Period,
);
```
which to me also seems like a bug, but maybe this is the expected behavior? Could you please mention the expected input for this function in the documentation?

I have found a temporary workaround, but I would appreciate a fix :)

Here is my workaround, if anyone needs it:
```dart
// example input
ThousandSeparator targetThousandSeparator = ThousandSeparator.Period;
double value = 1.0;

// workaround
String valueString = value.toString();
if ([ThousandSeparator.Period, ThousandSeparator.SpaceAndCommaMantissa].contains(targetThousandSeparator)) {
  valueString = valueString.replaceFirst('.', ',');
}

return toCurrencyString(
  valueString,
  thousandSeparator: targetThousandSeparator,
);
```

**Comment by fahami** [comment]
@nizioleque what if you use Period as thousand separator? is it multiplied by 10 also?

**Comment by nizioleque** [comment]
@fahami Yes, you can see this in the examples I provided.

**Comment by alod2019** [comment]
`14.35.toCurrencyString(thousandSeparator: ThousandSeparator.SpaceAndCommaMantissa)` 
gives **1 435,00**
so it just removes the dot when processing "14.35" string

**Comment by turtlepile** [comment]
thank you @nizioleque for the walkaround! having the same issue here..

waiting for the fix!

**Comment by eldarkk** [comment]
any fixes ? this issue became like a horror
