### ISSUE TITLE
`CurrencyInputFormatter` does not allow `.` as a trailing or leading symbol

### ISSUE THREAD

**Issue by nizioleque** [caseyryan/flutter_multi_formatter#117]
I would like to use `CurrencyInputFormatter` with the currency AWG (https://en.wikipedia.org/wiki/Aruban_florin) whose sign is "Afl.", with a period. `CurrencyInputFormatter` constructor throws an error and does not let me do that - how should I do it then?

**Comment by caseyryan** [comment]
Unfortunately, it's not possible
