### ISSUE TITLE
Possibility to filter the CountryDropdown widget items

### ISSUE THREAD

**Issue by payam-zahedi** [caseyryan/flutter_multi_formatter#118]
It's a common use case that sometimes we need to filter the countries 
For example, I need to limit the user to select from 3 countries. Not the whole countries 

We can have a `FilterItems` parameter or an `items` parameter for this widget.

Also, should mention that I can work on this issue

**Comment by caseyryan** [comment]
Hi! That's sounds like a good idea but unfortunately I don't have time for it at the moment

**Comment by payam-zahedi** [comment]
That's fine 
I'll take a look at it and create a PR

**Comment by payam-zahedi** [comment]
Is it closed? Can we do filter countries?

**Comment by caseyryan** [comment]
I'm not planning to add this functionality. You wanted to add it and make a pull request but there was no pull request after a few month, so I decided to close this thread
