### ISSUE TITLE
Distinguishing onCountrySelected triggers for CountryDropdown (user choosing versus initialCountryCode triggering)

### ISSUE THREAD

**Issue by RobHoman** [caseyryan/flutter_multi_formatter#122]
I noticed that using `initialCountryCode` for the `CountryDropdown` will cause `onCountrySelected` to trigger. I need a particular app behavior to respond only when `onCountrySelected` is triggered due to the user interaction, but I'm struggling to find a clean way to make the distinction.

Specifically, I want to move the focus to the next field in the form - the phone number text field - after the user selects the country. But since this triggers due to the `initialCountryCode` setting, my form is immediately focusing on the phone input, which is undesirable when the form is first loaded onto the screen.

If I could distinguish this somehow, that would solve my issues. Or, maybe you have thoughts on how better to integrate the CountryCode dropdown with the FocusNode conventions of Flutter and the conventions of Flutter forms?

**Comment by caseyryan** [comment]
CountryDropdown is there as an example. You can easily take it as a base and write your own widget. But I think that's a good point and I'll add the way to distinguish user selection from the default one

**Comment by caseyryan** [comment]
Fixed. Added a parameter called triggerOnCountrySelectedInitially. Just pass false and it will not be triggered on first build
