### ISSUE TITLE
Error: Type 'ValueChanged' not found

### ISSUE THREAD

**Issue by CocoaJerry** [caseyryan/flutter_multi_formatter#130]
I got these errors when I hot reloaded to the simulator iPhone 14

flutter: 2.10.5
dart: 2.16.0

: Error: Type 'ValueChanged' not found.
phone_input_formatter.dart:34
  final ValueChanged<PhoneCountryData?>? onCountrySelected;
        ^^^^^^^^^^^^
: Error: Expected 0 type arguments.
phone_input_formatter.dart:34
  final ValueChanged<PhoneCountryData?>? onCountrySelected;
        ^
: Error: 'ValueChanged' isn't a type.
phone_input_formatter.dart:34
  final ValueChanged<PhoneCountryData?>? onCountrySelected;
        ^^^^^^^^^^^^
: Error: Type 'ValueChanged' not found.
money_input_formatter.dart:62
  final ValueChanged<double>? onValueChange;
        ^^^^^^^^^^^^
: Error: Expected 0 type arguments.
money_input_formatter.dart:62
  final ValueChanged<double>? onValueChange;
        ^
: Error: 'ValueChanged' isn't a type.
money_input_formatter.dart:62
  final ValueChanged<double>? onValueChange;
        ^^^^^^^^^^^^
: Error: Type 'ValueChanged' not found.
credit_card_number_input_formatter.dart:46
  final ValueChanged<CardSystemData?>? onCardSystemSelected;
        ^^^^^^^^^^^^
: Error: Expected 0 type arguments.
credit_card_number_input_formatter.dart:46
  final ValueChanged<CardSystemData?>? onCardSystemSelected;
        ^
: Error: 'ValueChanged' isn't a type.
credit_card_number_input_formatter.dart:46
  final ValueChanged<CardSystemData?>? onCardSystemSelected;

**Comment by CocoaJerry** [comment]
These issues have no effect on running but will cause the failure of the version build

**Comment by caseyryan** [comment]
ValueChanged is the built in Flutter's typedef. It has nothing to do with the package
