### ISSUE TITLE
Bug in Armenian phone number

### ISSUE THREAD

**Issue by Veronika-dev** [caseyryan/flutter_multi_formatter#131]
Hey,
thank you for the plugin.

I tried to validate my phone number in Armenia which is formatted like +374 XXX XXX XX. However `isPhoneValid` function returns `false`. But I use my number, it is definitely correct.

Could you please add this format to the valid list of Armenian phones?

Thank you.

**Comment by caseyryan** [comment]
Hi! 
Yes, I'll add it as soon as I can. Thanks for the correction

**Comment by caseyryan** [comment]
Added in 2.11.5
