### ISSUE TITLE
initialCountryData not working

### ISSUE THREAD

**Issue by tgb2006** [caseyryan/flutter_multi_formatter#133]
initialCountryData: PhoneCountryData.fromMap({'country': 'India', 'phoneCode': '+91', 'countryCode': 'IN'})

not working it is just select the first country in the list

**Comment by caseyryan** [comment]
I don't understand what you're trying to do

**Comment by caseyryan** [comment]
I just checked it and it works. Use the approach like this
```
initialCountryData:
                              PhoneCodes.getPhoneCountryDataByCountryCode(
                            'IN',
                          ),
```

**Comment by mingg123** [comment]
hello. I also experienced the same issue and was able to solve it with the solution you mentioned. thank you!

`   initialCountryData: PhoneCodes.getPhoneCountryDataByCountryCode('KR'),`

**Comment by caseyryan** [comment]
> hello. I also experienced the same issue and was able to solve it with the solution you mentioned. thank you!
> 
> ` initialCountryData: PhoneCodes.getPhoneCountryDataByCountryCode('KR'),`

You're welcome. I'm glad that helped
