### ISSUE TITLE
Error Range start 5 is out of text of length 1

### ISSUE THREAD

**Issue by ferisetyo1** [caseyryan/flutter_multi_formatter#136]
I have error when using thousandSeparator period and mantissalength 0
inputFormatters: [
  CurrencyInputFormatter(
      thousandSeparator: ThousandSeparator.Period,
      mantissaLength: 0)
],

but is fine when :
inputFormatters: [
  CurrencyInputFormatter(
      thousandSeparator: ThousandSeparator.Comma,
      mantissaLength: 0)
],

or 
inputFormatters: [
  CurrencyInputFormatter(
      thousandSeparator: ThousandSeparator.Period,
      mantissaLength: 2)
],

**Comment by keblato** [comment]
Hi I have the same problem, mi output is file:///Users/kevin/fvm/versions/3.7.7/packages/flutter/lib/src/services/text_input.dart:963:12
range.start >= 0 && range.start <= text.length
"Range start 5 is out of text of length 1"


when mantissaLength is different from 0 I don´t have the exception but the number gets crazy with the comma in decimal number

**Comment by phanbaohuy96** [comment]
I have this issue also. any update?

**Comment by gokberkbar** [comment]
Hello, I have the same issue is there any update about this?

**Comment by ogedaysunar** [comment]
when will it be fixed? @caseyryan

**Comment by uygar** [comment]
I have this issue too. Any updates ?

**Comment by caseyryan** [comment]
Hi guys,
thanks for the report but unfortunately I don't have time for this at the moment, and I don't know when I find it. So I can't promise anything

**Comment by fatihyuksell** [comment]
I encounter this problem like other people. Can we give some priority to the solution?

**Comment by enesctn** [comment]
I have some problem. Any update?

**Comment by gokberkbar** [comment]
> Range start 5 is out of text of length 1

I might be able to create a PR for this issue

**Comment by caseyryan** [comment]
Added a quick solution to 2.12.1 
haven't really tested it though. But it fixes this issue
