### ISSUE TITLE
Нет форматирования после вставки российского номера с восьмеркой

### ISSUE THREAD

**Issue by doev03** [caseyryan/flutter_multi_formatter#137]
["хак специально для России"](https://github.com/caseyryan/flutter_multi_formatter/blob/dd6744996df7aba7f118aa16b57a5e46d8490e23/lib/formatters/phone_input_formatter.dart#L92) работает только если писать номер вручную. Часто пользователи предпочитают скопировать и вставить номер в поле, но в таком случае форматирование не срабатывает.
Не вижу проблем с тем, чтобы заменить этот блок на следующий:
```
if (shouldCorrectNumber && onlyNumbers.length >= 2) {
  /// хак специально для России, со вводом номера с восьмерки
  /// меняем ее на 7
  var isRussianWrongNumber =
      onlyNumbers[0] == '8' && onlyNumbers[1] == '9' ||
          onlyNumbers[0] == '8' && onlyNumbers[1] == '3';
  if (isRussianWrongNumber) {
    onlyNumbers = '7${onlyNumbers.substring(1)}';
    _countryData = null;
    _applyMask(
      '7',
      allowEndlessPhone,
    );
  }

  final isAustralianPhoneNumber =
      onlyNumbers[0] == '0' && onlyNumbers[1] == '4';
  if (isAustralianPhoneNumber) {
    onlyNumbers = '61${onlyNumbers.substring(1)}';
    _countryData = null;
    _applyMask('61', allowEndlessPhone);
  }
}
```
Поправьте меня, если я где-то ошибаюсь.

**Comment by caseyryan** [comment]
О какой версии флаттера идет речь? Они там постоянно что-то меняют. По идее нет никакой разницы вставка это или ручной ввод, колбек все равно должен отработать так же

**Comment by doev03** [comment]
> О какой версии флаттера идет речь? Они там постоянно что-то меняют. По идее нет никакой разницы вставка это или ручной ввод, колбек все равно должен отработать так же

Возможно, вы неправильно поняли. Если вставить номер с восьмеркой целиком, условие `onlyNumbers.length == 2` не выполнится, т.к. `onlyNumbers` будет равен `8##########`.

**Comment by caseyryan** [comment]
Аа, всё, теперь понял. Да, разумно. Поправлю это, спасибо

**Comment by caseyryan** [comment]
Добавлено в версии 2.11.12
