### ISSUE TITLE
Ascension Island can't find

### ISSUE THREAD

**Issue by sunlimiter** [caseyryan/flutter_multi_formatter#138]
{
        'country': 'Ascension Island',
        'countryRU': 'Ascension Island',
        'internalPhoneCode': '247',
        'countryCode': 'AC',
        'phoneMask': '+xxxxxxx',
      }

**Comment by caseyryan** [comment]
What is the correct phone mask for it?

**Comment by sunlimiter** [comment]
@caseyryan 
I'm not sure, this plugin is only used as a national flag search, and I found that there is one less Ascension Island
