### ISSUE TITLE
replacePhoneMask works only in debug mode

### ISSUE THREAD

**Issue by GurgenHOVH** [caseyryan/flutter_multi_formatter#143]
`replacePhoneMask` works only in debug mode. 

The code section to replace the mask will only work if the following condition is true

```dart
 if (currentMask != newMask && kDebugMode) {
```

Here the kDebugMode is useless and should be removed. Otherwise please document why kDebugMode is used here.

**Comment by GurgenHOVH** [comment]
PR #142 should close this.

**Comment by caseyryan** [comment]
Merged that PR
