### ISSUE TITLE
email format

### ISSUE THREAD

**Issue by andim27** [caseyryan/flutter_multi_formatter#144]
Please add email format like this:  inputFormatters: [EmailInputFormatter()],

**Comment by caseyryan** [comment]
> Please add email format like this: inputFormatters: [EmailInputFormatter()],

Does an email have some special format? I can't event imaging the functionality of email formatter

**Comment by andim27** [comment]
May by *.com,*.info *gmail.com etc ?

**Comment by caseyryan** [comment]
No, it's not a formatter's business to think for a user. If you need something like this, you'll have to implement your custom mechanism
