### ISSUE TITLE
Некорректная позиция курсора

### ISSUE THREAD

**Issue by mtrfnvwork** [caseyryan/flutter_multi_formatter#146]
Когда курсор стоит после `trailingSymbol`, то при вводе он остается на том же месте. Было бы логично переносить его в конец вводимой суммы, то есть перед `trailingSymbol`

https://github.com/caseyryan/flutter_multi_formatter/assets/61468224/8526e8e4-3bf5-4c5e-8284-69f701058243

**Comment by caseyryan** [comment]
Может быть. Но это низкий приоритет, есть более важные задачи сейчас. Если очень нужно, и есть желаение, можете исправить это, и сделать МР, если всё ок, я его вмержу. Обещать, что сам в какое-то ближайшее время смогу этим заняться, я не могу
