### ISSUE TITLE
When a zero is entered in the decimal part, the cursor moves to the begining positon of whole part

### ISSUE THREAD

**Issue by quan-codemetrics** [caseyryan/flutter_multi_formatter#15]
When entering 4.06. It becomes 64.0

![image](https://user-images.githubusercontent.com/70996524/95811901-79f27b80-0d3e-11eb-9477-d15231d358db.png)

**Comment by caseyryan** [comment]
Yes, I know about this bug and I have already fixed it locally. But I need to apply it also for the numbers with comma as a decimal separator. Hopefully I will update the package  with fixes this weekend

**Comment by quan-codemetrics** [comment]
Thank you @caseyryan. You're a hero.

**Comment by caseyryan** [comment]
Fixed in version 1.2.0 
Important notice, now it requires Flutter 1.22.4 and dart 2.10.2+ 
Flutter 1.23.0 and newer are not supported yet but will be as soon as they become stable
