### ISSUE TITLE
Incomplete uzcard format

### ISSUE THREAD

**Issue by Caypoh23** [caseyryan/flutter_multi_formatter#150]
Upon the 8600 format, Uzcard also has 5614 systemCode
```
{
      'system': CardSystem.UZ_CARD,
      'systemCode': '8600',
      'numberMask': '0000 0000 0000 0000',
      'numDigits': 16,
}
```

This is based on https://1pay.uz/blog/chto-oboznachayut-czifry-na-platezhnyh-kartah/

Moreover, I added the Humo system but cannot push the changes to a new branch because the permission was denied so there is no possibility to create a pull request. 
   ```
 {
      'system': CardSystem.UZ_CARD,
      'systemCode': '5614',
      'numberMask': '0000 0000 0000 0000',
      'numDigits': 16,
    },
    {
      'system': CardSystem.HUMO,
      'systemCode': '9860',
      'numberMask': '0000 0000 0000 0000',
      'numDigits': 16,
    },
```

**Comment by caseyryan** [comment]
Thanks. Added your fixes to 2.12.4
