### ISSUE TITLE
Canada and USA by phone number

### ISSUE THREAD

**Issue by MaximSamolovov** [caseyryan/flutter_multi_formatter#167]
Hello! How to distinguish Canada and the USA by phone number? Do these countries have the same phone code "+1" Is there an easy way to do this? Now there is a problem that when initializing the input, the US country is selected for the Canadian number

**Comment by caseyryan** [comment]
There's no easy way to do it. You should implement your own logic for detecting the country, maybe using some backend or a more advanced dictionary that will check the region code as well
