### ISSUE TITLE
Add a 3-digit ISO country code

### ISSUE THREAD

**Issue by MaximSamolovov** [caseyryan/flutter_multi_formatter#168]
Currently, only two-digit country codes are available, because in most cases the list of countries rarely changes, it is convenient to use the countries from PhoneCodes.getAllCountryDatas(), but there are not enough three-digit country codes, without them the data is incomplete. you can also add currencies, because the library's functionality is designed not only for phone numbers

**Comment by caseyryan** [comment]
I don't need it in any of my projects. I will add it if I ever need it. It all requires time which I don't have. 
So if you need it, you can always add this functionality and make a pull request I will gratefully merge it
