### ISSUE TITLE
MaskedInputFormater does not format entire strings correctly

### ISSUE THREAD

**Issue by gabrielgarciagava** [caseyryan/flutter_multi_formatter#17]
If you paste an entire string on a TextField with a MaskedInputFormater at once, it will not format correctly.

Use case:
Create a TextField with a MaskedInputFormater('### ### ###')
Paste the string 123456789 on this TextField
It will be formated as `123 345 567` instead of `123 456 789`

**Comment by gabrielgarciagava** [comment]
I fixed the issue locally. I will open a PR soon.

**Comment by VladanRandjelovic** [comment]
is this fix going to be up for updating pub soon? also i have issues when deleting from TextField with mask ('(###) ###-####') it breaks the mask removing the - sign on first press of backspace

**Comment by gabrielgarciagava** [comment]
No idea @VladanRandjelovic 
I did not see any activity of the author so far. Not sure how often he updates this lib.

**Comment by caseyryan** [comment]
Fixed
