### ISSUE TITLE
Add the ability to use dot (.) as ThousandSeparator

### ISSUE THREAD

**Issue by brizaldi** [caseyryan/flutter_multi_formatter#2]
something like this: $1.000.000

**Comment by caseyryan** [comment]
I thought about this. But in this case a decimal part must be separated with comma which is not correct afaik. If I use dots for thousand separators and for a decimal part, the formatter will break

**Comment by brizaldi** [comment]
> I thought about this. But in this case a decimal part must be separated with comma which is not correct afaik. If I use dots for thousand separators and for a decimal part

There are many country that use dots for thousand separator and comma for decimal

**Comment by caseyryan** [comment]
> > I thought about this. But in this case a decimal part must be separated with comma which is not correct afaik. If I use dots for thousand separators and for a decimal part
> 
> There are many country that use dots for thousand separator and comma for decimal

I didn't know that. Ok, I'll add this functionality

**Comment by caseyryan** [comment]
I've added this possibility in version 1.1.6. Now if you need periods instead of commas as a thousand separators, bimply use 
```dart 
MoneyInputFormatter(
   thousandSeparator: ThousandSeparator.Period
);
```
and you'll get 1.000.000,00 instead of 1,000,000.00

If there's an issues related to this, feel free to reopen this thread. For now I close it
