### ISSUE TITLE
The phone number is not formatted when erased

### ISSUE THREAD

**Issue by NiyazFazlyev** [caseyryan/flutter_multi_formatter#22]
When creating a TextField I set the initial text to controller and then start erasing the text, but text is not formatted if I enter back at least one deleted character formatting occurs

**Comment by caseyryan** [comment]
I know about this behavior but I can't promise I'll fix it in some near future. I just don't have time enough

**Comment by caseyryan** [comment]
fixed in version 1.3.3 https://pub.dev/packages/flutter_multi_formatter
