### ISSUE TITLE
Default Constructor

### ISSUE THREAD

**Issue by panalgin** [caseyryan/flutter_multi_formatter#25]
Wouldn't it be cool if there was a default constructor for PhoneCountryData so we could show an initial value on UI? (Based on users device locale, I am able to get the user's countryCode). I can send a pull request if you see it fits

Thanks, great package by the way kudos

**Comment by caseyryan** [comment]
Sure, feel free to make a pull request. It would be a good feature but unfortunaltely I don't have time enough to implement the features myself too often. So I'm glad if there are other contributors to the project
>> Thanks, great package by the way kudos
You're welcome =) Glad you like it

**Comment by caseyryan** [comment]
No replies ever since, so I'm closing the issue for now
