### ISSUE TITLE
Don't hide keyboard on scroll event

### ISSUE THREAD

**Issue by Apollo108** [caseyryan/flutter_multi_formatter#29]
Hi, thank you for the package and your efforts, please, make the keyboard hiding behaviour customizable, e.g. it would be nice to hide it not on a scroll event, but on a tap. Thank you!

**Comment by caseyryan** [comment]
I've just uploaded an update. Version 1.3.6 and added a minScrollDistance parameter to Unfocuser. 
By default it's set to 10 pixels. This means if you touch and drag your finger more than 10 pixels (in any direction) it will consider this as scrolling/dragging and will not take focus off of the current input. If, for some reason, you want it to always unfocus the input, just set this parameter to 0.0 or null
