### ISSUE TITLE
Unfocuser fails when clicking on another editable

### ISSUE THREAD

**Issue by Grooviz** [caseyryan/flutter_multi_formatter#30]
### Description:
Unfocuser fails to unfocus a TextField when clicking on a Button.

### How to reproduce:

The following Flutter App creates a TextField, a Container, and an ElevatedButton.

```
import 'package:flutter/material.dart';
import 'package:flutter_multi_formatter/flutter_multi_formatter.dart';

void main() {
  runApp(
    MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Scan with',
      home: Scaffold(
        body: Unfocuser(
          child: Padding(
            padding: const EdgeInsets.all(16.0),
            child: Column(
              children: [
                TextField(
                  decoration: InputDecoration(hintText: 'Text field'),
                ),
                const SizedBox(height: 24),
                Container(width: 150, height: 60, color: Colors.blueGrey),
                const SizedBox(height: 24),
                ElevatedButton(
                  onPressed: () {},
                  child: Text('BUTTON'),
                )
              ],
            ),
          ),
        ),
      ),
    ),
  );
}
```

![unfocuser](https://user-images.githubusercontent.com/44902700/106753217-aef74680-662b-11eb-8adf-d212d88e8db9.gif)

- Path 1: Focus on the TextField, click on the Container ⇒ TextField is unfocused. 
- Path 2: Focus on the TextField, click on the ElevatedButton ⇒ TextField is not unfocused.

### What we expect:

With Path 2, the TextField should get unfocused. It should get unfocused when clicking on any (editable or not) other parts of the application.

I'm searching for a way to fix this, but with no success so far... Do you know a workaround?

Thanks a lot!

**Comment by caseyryan** [comment]
Hi, sorry for the late reply, I do not get notifications about new issues for some reason
It's not a bug.
You can try two things:
1) Instead of wrapping the Padding into Unfocuser, wrap the whole Scaffold instead. 
2) Wrap your button into  ForceUnfocuser() widget (which was made exactly for this purpose). It's located in the same file as Unfocuser itself
