### ISSUE TITLE
phone formatter delete key doesn't work on dev channel

### ISSUE THREAD

**Issue by sgehrman** [caseyryan/flutter_multi_formatter#31]
seems to work on stable branch

**Comment by sgehrman** [comment]
doesn't work on beta branch either.

**Comment by sgehrman** [comment]
Looks like it's fixed in master now:   https://github.com/flutter/flutter/pull/75541

**Comment by caseyryan** [comment]
It is not related to my package so I'm closing the issue for now

**Comment by sgehrman** [comment]
I'm on flutter 2 stable branch now, doesn't work.  Not sure why that fix didn't make it in.
