### ISSUE TITLE
null-safety support!

### ISSUE THREAD

**Issue by Ali-Fadaei** [caseyryan/flutter_multi_formatter#33]
with flutter v2.0.0, Dart's sound null-safety is stable now, so for safe migrate projects to it, flutter recommended wait for migration of all project dependencies to null-safety, I have project depended on this awesome flutter plugin, please migrate it 🙏🏻

**Comment by caseyryan** [comment]
I will as soon as I have time to move my work projects to new Flutter. Hopefully next week. Unfortunately I'm overloaded with work at the moment so I can't keep up with all the requirements

**Comment by caseyryan** [comment]
Null-safe version is out now! https://pub.dev/packages/flutter_multi_formatter 
I've also fixed some bugs there. There you go =)

**Comment by Ali-Fadaei** [comment]
@caseyryan Thanks
