### ISSUE TITLE
ThousandSeparator.None not working

### ISSUE THREAD

**Issue by VisualMafia** [caseyryan/flutter_multi_formatter#35]
Hi, I want to remove the separation entirely, but it doesn't work.

MoneyInputFormatter(useSymbolPadding: true, mantissaLength: 2, thousandSeparator: ThousandSeparator.None),

I want to make the separation only with a space

15.000,00 => 15 000,00

**Comment by caseyryan** [comment]
ThousandSeparator.None means NO separator at all. In your case ThousandSeparator.SpaceAndPeriodMantissa would do. But it's indeed has broken. I'll take a look into this

**Comment by caseyryan** [comment]
I've fixed it in version 2.0.0 today. But the version requires null safety so it might be a problem if your project still uses Flutter version below 2.0.0. Anyway, I'm not planning to support old versions anymore. 
In your case just use ThousandSeparator.SpaceAndPeriodMantissa 
I'm closing the issue for now

**Comment by VisualMafia** [comment]
Thanks!
