### ISSUE TITLE
It's not possible to print '+' sign in PhoneNumberFormatter

### ISSUE THREAD

**Issue by AlexandrFarkas** [caseyryan/flutter_multi_formatter#45]
Is it possible to allow user to input '+' sign? It's a bit strange, because '+' is eventually printed anyway.

**Comment by caseyryan** [comment]
I don't think it's ever necessary

**Comment by karabanovbs** [comment]
'+'  printed only if country detected.
You cant try wrap PhoneInputFormatter in you custom input formater, that handle when '+' is type.

**Comment by AlexandrFarkas** [comment]
@caseyryan User starts typing his international number, and sees that '+' is not even printed.
It affect UX badly. So why is it not necessary?

**Comment by AlexandrFarkas** [comment]
@karabanovbs I already tried. And it's not really possible, 'cause formatter erases +, if it doesn't find country, having this digit.
For example, when I type '+7' , it persists. But when I type '+4', '+' is erased (result is just '4').

**Comment by karabanovbs** [comment]
@AlexandrFarkas 
It is possible. Something like this:
```
class AllowPlusCodeFormatter extends TextInputFormatter {
  @override
  TextEditingValue formatEditUpdate(
      TextEditingValue oldValue, TextEditingValue newValue) {
      var origin = PhoneInputFormatter.formatEditUpdate(oldValue, newValue);
    if (!origin.text.startsWith('+') && newValue.text.startsWith('+') {
      return newValue;
    } else {
      return origin;
    }
  }
}
```

**Comment by AlexandrFarkas** [comment]
@karabanovbs Thanks a lot for help. Closing

**Comment by caseyryan** [comment]
> @karabanovbs I already tried. And it's not really possible, 'cause formatter erases +, if it doesn't find country, which has this digit.
> For example, when I type '+7' , it persists. But when I type '+4', '+' is erased (result is just '4').

What country code starts with +4? If there is such a country and it's not on the list, I will add it. But the way you propose to solve the problem is not correct. It ruins the whole idea of an automated formatter
