### ISSUE TITLE
Something wrong with RU and KZ phone code

### ISSUE THREAD

**Issue by karabanovbs** [caseyryan/flutter_multi_formatter#47]
Why KZ code is [77](https://github.com/caseyryan/flutter_multi_formatter/blob/master/lib/formatters/phone_input_formatter.dart#L1061)?

Wikipedia says that Kz and Ru have the same code:
[Kazakhstan](https://en.wikipedia.org/wiki/Telephone_numbers_in_Kazakhstan)
[Russia](https://en.wikipedia.org/wiki/Telephone_numbers_in_Russia)

How we can detect Kz phone?

**Comment by caseyryan** [comment]
I've rejected this commit because it has an incorrect solution. You are right about 7 but it's not because I've mistakingly did it. It's for another reason. I'll make a correct way to get a real phone code later

**Comment by caseyryan** [comment]
It's fixed in version 2.1.2. Now phoneCode property will return correct code 7 for Kazakhstan but internal code for the system now lives in 'internalPhoneCode' property not accessible from the outside
