### ISSUE TITLE
ThousandSeparator.Period doesnt work when using it inside TextFormField

### ISSUE THREAD

**Issue by brizaldi** [caseyryan/flutter_multi_formatter#5]
when i try to use ThousandSeparator.Period inside textformfield the value doesnt change, it still showing commas

`TextFormField(
  inputFormatters: [
    MoneyInputFormatter(
      thousandSeparator: ThousandSeparator.Period,
      mantissaLength: 0,
    ),
  ],
  ...
)`

![image](https://user-images.githubusercontent.com/41714881/81028098-4c112d00-8eaa-11ea-8b4c-73374e04d965.png)

i also have another issue while using ThousandSeparator.Period, it seems the value is capped at maximum 7 digit

**Comment by Sun3** [comment]
Any updates on this issue?

Thanks

**Comment by caseyryan** [comment]
The logic of a formatter was completely changed in 1.2.0. This issue is fixed as well
