### ISSUE TITLE
ThousandSeparator.None not working

### ISSUE THREAD

**Issue by LudmilKirov** [caseyryan/flutter_multi_formatter#50]
Hi, I want to remove the separation entirely, but it doesn't work.

  MoneyInputFormatter(
                thousandSeparator: ThousandSeparator.None,leadingSymbol: MoneySymbols.POUND_SIGN),

I want to make the separation without separator

150,000.00 => 150000.00

**Comment by caseyryan** [comment]
Thanks, I'll check it

**Comment by caseyryan** [comment]
Fixed in version 2.2.0
