### ISSUE TITLE
unmasked value

### ISSUE THREAD

**Issue by Mirshodbek** [caseyryan/flutter_multi_formatter#52]
Hello. I have question. How can I get unmasked value?  Thank

**Comment by caseyryan** [comment]
Hi! 
There is no way to do it. The unmasked values is not stored anywhere, so the only way to do so is to not use any formatter

**Comment by rodion-m** [comment]
@caseyryan But what about `unmasked` getter from PhoneInputFormatter?

**Comment by Bringoff** [comment]
I use `toNumericString` utility function for that.
