### ISSUE TITLE
documentation page needs an update!

### ISSUE THREAD

**Issue by sachin-dahal** [caseyryan/flutter_multi_formatter#53]
A big thanks for the package...
As I was looking towards the main documentation for the usage of the package, I've witnessed few things on the documentation page which need to gets fixed.
A few improvements in the documentation page can be done as it will be easier for many package users to get used to with the package.
:)

**Comment by caseyryan** [comment]
Thanks for your cooperation. Merged. 
There's a few more things that need updating but I always have too little time to do it :D
