### ISSUE TITLE
Hungary phone mask incorrect

### ISSUE THREAD

**Issue by Szabocsongi576** [caseyryan/flutter_multi_formatter#57]
Hey!

I discovered a phone mask mismatch. The correct hungarian mask is +00 00 000 0000, so one more digit in the end (Current mask is +00 00 000 000).  Everything else is correct.

**Comment by caseyryan** [comment]
Hi!
Is the mask you've provided used for all numbers? Or do I have to add both?

**Comment by Szabocsongi576** [comment]
Hi!
Sorry, I just focused to mobile numbers. So
- mobile numbers: +36 00 000 0000 or 06 00 000 0000
- local area numbers: +36 00 000 000 or 06 00 000 000 (Budapest is unique: +36 1 000 0000 or 06 1 000 0000)

**Comment by caseyryan** [comment]
> Hi!
> Sorry, I just focused to mobile numbers. So
> 
> * mobile numbers: +36 00 000 0000 or 06 00 000 0000
> * local area numbers: +36 00 000 000 or 06 00 000 000 (Budapest is unique: +36 1 000 0000 or 06 1 000 0000)
So, if I understand correctly I need to add these masks
00 0 000 0000 // is it's Budapest
00 00 000 0000 // covering +36 and 06
Is that correct?

**Comment by Szabocsongi576** [comment]
Yes. The +36 is the international prefix, the 06 can be used to domestic calls.

**Comment by caseyryan** [comment]
Fixed in version 2.3.5.
