### ISSUE TITLE
RangeError thrown when calling toCurrencyFormat() with value without period and mantissaLength = 0

### ISSUE THREAD

**Issue by EstebanCardenas** [caseyryan/flutter_multi_formatter#62]
Whenever a value without period is sent and the mantissaLength prop is set to 0, a RangeError is thrown. 

Example:

`toCurrencyString('2545', mantissaLength: 0)`

Expected:

`2,545`

Instead RangeError is thrown.

![image](https://user-images.githubusercontent.com/53832358/135552330-ed39b1b9-46a2-4142-a0bd-8e25670057c1.png)

This is because line 565 returns -1 since there are no periods in the value, and then line 566 attempts to take a substring from 0 to -1.

**Comment by caseyryan** [comment]
Thanks. Fixed
