### ISSUE TITLE
Thousand Separator by Locale

### ISSUE THREAD

**Issue by 0xPixelfrost** [caseyryan/flutter_multi_formatter#66]
Hi,

would it be possible to provide the ThousandSeparator by the users locale settings instead of defining it fix during initialisation?

**Comment by caseyryan** [comment]
Hi,
I don't need it in any projects a develop. I believe some people might have a need for that but, unfortunately I don't have free time for it. If you can implement it (as an option) and make a pull request, I'd be grateful. But I cannot promise I will implement it myself in any near future, so I'll close this issue for now
