### ISSUE TITLE
MoneyInputFormatter unexpected behavior with leading zero

### ISSUE THREAD

**Issue by 0xPixelfrost** [caseyryan/flutter_multi_formatter#67]
If i start a MoneyInputFormatter input with a "0" , the cursor jumps directly to the decimal points - which is uncommon compared to a regular calculator.
When i enter a decimal point next, the cursor moves on sept more to the right.

Entering the input  `0 . 9` results in `0.09`
I would expect the result `0.9`

**Comment by caseyryan** [comment]
The way it works now is how I needed it to work. I gave it a test and it works exactly as I planned it, no bugs or unexpected behavior. If you think this behavior is not appropriate for your project, feel free to make a fork repo and implement a custom functionality, then you can connect it to your project like this 
```
flutter_multi_formatter:
    git:
      url: git://github.com/OxPixelFrost/flutter_multi_formatter.git
```
