### ISSUE TITLE
Tp

### ISSUE THREAD

**Issue by mayanktolani19** [caseyryan/flutter_multi_formatter#68]
Please change the spelling of MaskedInputFormater to MaskedInputFormatter (a 't' is missing). It can be misleading at some times. I was wondering for 5 minutes as to why was it not working, then found the typo xD.
  
![image](https://user-images.githubusercontent.com/44107923/143736005-a5a1ead2-af07-4591-a465-e46c14ab16a0.png)

**Comment by caseyryan** [comment]
Thanks! I'll change it as soon as I can

**Comment by caseyryan** [comment]
fixed in 2.4.4
