### ISSUE TITLE
Valid through\n (this formatter won\'t let you type the "month" part value larger than 12)

### ISSUE THREAD

**Issue by Shahmirzali-Huseynov** [caseyryan/flutter_multi_formatter#70]
it's not working. I tried in example.   AND  also cvc  3 decimal number not 4.
<img width="263" alt="Screen Shot 2021-12-13 at 22 09 52" src="https://user-images.githubusercontent.com/49102327/145873305-40960de4-e2f9-4106-96b8-be068352e7a0.png">

**Comment by caseyryan** [comment]
Thanks. I'll take a look at this

**Comment by caseyryan** [comment]
Fixed in 2.5.1
