### ISSUE TITLE
If value loaded to TextFormField via "initialValue" property, formatting is not working

### ISSUE THREAD

**Issue by booooohdan** [caseyryan/flutter_multi_formatter#72]
I pass via "InitialValue" string '4141554455667898', or '0222', and it's not formatted. But when I trigger TextForm manually (add or delete symbol) formatting starts working. Please fix, your library is very useful

![Screenshot 2021-12-20 at 18 19 05](https://user-images.githubusercontent.com/30977443/146798968-08d89f32-4e47-49be-bcf1-7569f6096f67.png)

**Comment by caseyryan** [comment]
Hi! 
Sorry but this library has nothing to do with TextFormField or any other Form widgets. It's TextFormField that should trigger its formatters not the other way round. I can't do anything with that. But you can set initialValue using internal utility methods of my library. E.g. 
```dart
TextFormField(
   initialValue: toCurrencyString(yourValueGoesHere),
)
```

**Comment by Upsurgeinc** [comment]
Hi Bohdan, do you have any contact information for hire?

**Comment by AppetiteTeam** [comment]
**How to do the same for the phone?**
toPhoneString() i didn't found.

initialValue: phone

**Comment by caseyryan** [comment]
> **How to do the same for the phone?** toPhoneString() i didn't found.
> 
> initialValue: phone

Use ```formatAsPhoneNumber()``` from this class https://github.com/caseyryan/flutter_multi_formatter/blob/master/lib/formatters/phone_input_formatter.dart

**Comment by AppetiteTeam** [comment]
> 

Sorry, I just got around to checking it out.
Thanks, it works =)

**Comment by caseyryan** [comment]
You're welcome. 
I think I need to add more intuitively named functions for it and more consistent. They're called so differently because they were developed at different times independently of each other
