### ISSUE TITLE
Add space in MaskedInputFormatter()

### ISSUE THREAD

**Issue by marceloamp2** [caseyryan/flutter_multi_formatter#73]
How can I add a space after the ')' in MaskedInput Format('(00) 00000-0000')? Inserted space did not work

Example: (99) 99999-9999

**Comment by sharpsan** [comment]
Same problem here.  Is this a regex issue?

**Comment by caseyryan** [comment]
Space is added automatically. You simply type the next symbol and if a mask contains space, it should be added itself

**Comment by sharpsan** [comment]
> Space is added automatically. You simply type the next symbol and if a mask contains space, it should be added itself

Spaces are not working as intended, then.

**Comment by caseyryan** [comment]
I'll check when I have time. Most probably it has been broken by one of the latest pull requests

**Comment by sharpsan** [comment]
> I'll check when I have time. Most probably it has been broken by one of the latest pull requests

Thank you!

**Comment by Yahllil** [comment]
Any update with this? It doesn't work for me either
