### ISSUE TITLE
The cursor always stays in right when using PosInputFormatter.

### ISSUE THREAD

**Issue by SittiphanSittisak** [caseyryan/flutter_multi_formatter#75]
I just use inputFormatters: const [PosInputFormatter()].

https://user-images.githubusercontent.com/59549741/151492822-b3a2680a-9330-4b0e-8589-173540f3673d.mp4

**Comment by caseyryan** [comment]
It's an intended behavior for a Point Of Sale input type. Use MoneyInputFormatter if you need normal input
