### ISSUE TITLE
Format phone number without country code

### ISSUE THREAD

**Issue by Prn-Ice** [caseyryan/flutter_multi_formatter#78]
Hi I have a phone field widget like this 
<img width="415" alt="Screenshot 2022-02-12 at 23 44 27" src="https://user-images.githubusercontent.com/48252841/153731216-d77c943d-8bc1-4b52-b505-57bbc394dfc4.png">

- The user selects the country before they start typing.
- My textfield also annotates `+countryCode` on every change.

The `PhoneInputFormatter` currently only works when I start typing the country code.
<img width="415" alt="Screenshot 2022-02-12 at 23 54 52" src="https://user-images.githubusercontent.com/48252841/153731385-11bb8c3d-dae3-42eb-8ea8-0653d365aee1.png">

Could it be possible to add a toggle that formats the input without adding the `+countryCode`.

**Comment by caseyryan** [comment]
Hi,
I'm not planning to add this functionality, sorry
