### ISSUE TITLE
Cursor offset error

### ISSUE THREAD

**Issue by tologonkudaiberdiuulu** [caseyryan/flutter_multi_formatter#80]
Please fix cursor offset when deleting if for trailingSymbol was given string with length more than one. It's jumping to left after every delete symbol.

E.g code:
`
import 'package:flutter/material.dart';
import 'package:flutter_multi_formatter/flutter_multi_formatter.dart';

class Test extends StatelessWidget {
  const Test({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Test'),
      ),
      body: Form(
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 20),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              TextFormField(
                inputFormatters: [
                  MoneyInputFormatter(
                    thousandSeparator: ThousandSeparator.SpaceAndPeriodMantissa,
                    trailingSymbol: ' USD',
                  ),
                ],
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: 40),
              SizedBox(
                height: 50,
                child: Padding(
                  padding: const EdgeInsets.symmetric(horizontal: 40),
                  child: ElevatedButton(
                    child: const Text('Tap'),
                    onPressed: () {
                    },
                  ),
                ),
              )
            ],
          ),
        ),
      ),
    );
  }
}
`

Type any big value. Say, 123123123. My cursor standing after third 3. After deleting 3, my cursor jumps to between third 1 and 2 rather than just deleting 3 and staying at last position after 2.

**Comment by WingCH** [comment]
same issue
