### ISSUE TITLE
PhoneInputFormatter: Allow '+' to be entered

### ISSUE THREAD

**Issue by vHanda** [caseyryan/flutter_multi_formatter#85]
Hi. I'd love it if when I press the "+" button, a "+" would appear, instead of nothing. It took me sometime to figure out that the + would be added automatically.

Please let me know if this is a behavior you'd accept, and I'll see if/when I can find the time to contribute.

**Comment by caseyryan** [comment]
Hi! Yes, you're right. I also had this request from other people but I still had no time to implement it, unfortunately. Too loaded with work :(

**Comment by vHanda** [comment]
Thank you. You're amazing.

**Comment by caseyryan** [comment]
I have't pushed the project to pub.dev yet, because there's another bug fix in progress
