### ISSUE TITLE
Currency input formatter empty value error

### ISSUE THREAD

**Issue by Sancene** [caseyryan/flutter_multi_formatter#87]
when i erase my currency value it becomes 0 and then if i type new numbers to that input field it doesn't erase the zero and leaves it at the start of the text

**Comment by caseyryan** [comment]
can you provide some code snippet to reproduce this?

**Comment by caseyryan** [comment]
https://user-images.githubusercontent.com/4113558/185744967-644b5a6f-cdff-4620-9fd5-6c2609f47275.mov

I've just checked it, and it works just fine

**Comment by caseyryan** [comment]
Oh, I found one way to reproduce it. Is when you specify a 0 mantissa length. Ok, thanks for the report. I'll fix this

**Comment by caseyryan** [comment]
Fixed in 2.6.1. I also found 2 related bugs and fixed them as well

**Comment by Sancene** [comment]
Thanks for the fix but there is another bug related to mantissa length being 0: if your cursor is set on the trailing symbol you are not able to delete but are able to type.

**Comment by caseyryan** [comment]
It's not a bug, it's planned this way

**Comment by Sancene** [comment]
but if i set mantissa to 1 then i am able to delete input value. It displaces cursor to value first, bypassing the trailing symbol but i am still able to delete after that.

**Comment by Sancene** [comment]
https://user-images.githubusercontent.com/56795876/185872122-ff61cdd1-12b2-4507-8da0-22d61f8a13bb.mp4

**Comment by asadamatic** [comment]
@caseyryan I'm facing the issue that's mentioned in very first comment. I understand that you had fixed it, but I'm encountering it.

**Comment by asadamatic** [comment]
https://github.com/user-attachments/assets/2ac7f8ce-0d5d-4992-a3d4-df9ffae77445


https://github.com/user-attachments/assets/e7bc8075-7f37-4405-b9cd-5e4e39e07407

**Comment by asadamatic** [comment]
Thanks, I'll try it
