### ISSUE TITLE
onValueChange is never called

### ISSUE THREAD

**Issue by renanboni** [caseyryan/flutter_multi_formatter#89]
Hi, I'm implementing a TextField with CurrencyInputFormatter and I wanted to use onValueChanged callback to get the double value, but it's never called and actually, from what I've seen in the source code, you're not even using it

**Comment by caseyryan** [comment]
Hi! Yes, I forgot to remove this callback from the constructor. It can't be used in a reliable manner because I  don't use double.tryParse any more since it fails on some huge numbers.
