### ISSUE TITLE
Giving Exception while running the app

### ISSUE THREAD

**Issue by ashtp96** [caseyryan/flutter_multi_formatter#94]
flutter/.pub-cache/hosted/pub.dartlang.org/flutter_multi_formatter-2.7.2/lib/widgets/country_dropdown.dart:176:7: Error: No named parameter with the name 'borderRadius'.
      borderRadius: widget.borderRadius,
      ^^^^^^^^^^^^
flutter/packages/flutter/lib/src/material/dropdown.dart:1514:3: Context: Found this candidate, but the arguments don't match.
  DropdownButtonFormField({

Getting build crash on running app. 
![Capture](https://user-images.githubusercontent.com/89844440/188447643-c9436881-d809-4708-8a27-24985c1db159.PNG)

**Comment by ashtp96** [comment]
It was flutter sdk version issue. I was using 2.5.10. Fixed by changing sdk version to 3.0.1

**Comment by milkyway044** [comment]
+1 the same exception while running the app with Flutter 2.10.5.

I'm not ready to update flutter sdk to 3.0. 
Which package version can be used with flutter 2.10.5 ?

**Comment by milkyway044** [comment]
looks like version `flutter_multi_formatter: 2.6.0` works with flutter 2.10.5

**Comment by caseyryan** [comment]
I'll remove this parameter in the next version. But if you need this version to work with older Flutter you can just copy/paste this CountryDropdown and make your own version of it without borderRadius. There's nothing special inside.
