### ISSUE TITLE
Bug with CreditCardExpirationDateFormatter

### ISSUE THREAD

**Issue by alfredo-handcash** [caseyryan/flutter_multi_formatter#96]
Hi! First of all, thanks for your time creating this package! Is amazing.

I found a bug from the 2.5.1 version in the `CreditCardExpirationDateFormatter` when you try to enter a January month, in this [video](https://transfer.sh/swJ3SB/formatter%20issue.mp4) you can see an example.

I think is related with this change: https://github.com/caseyryan/flutter_multi_formatter/blob/master/lib/formatters/credit_card_expiration_input_formatter.dart#L76

Thanks for your time!

**Comment by caseyryan** [comment]
hi! Thank you! I'm glad people like my package
I'll take a look at this

**Comment by caseyryan** [comment]
Thanks again for your report. It was a really critical issue. Fixed in 2.7.5
