### ISSUE TITLE
CurrencyInputFormatter doesn't allow to input mantissa after entering dots/commas

### ISSUE THREAD

**Issue by TimYusR** [caseyryan/flutter_multi_formatter#98]
Hi!

I have an issue with CurrencyInputFormatter. 
I use `ThousandSeparator.Comma`.
When I enter a dot or comma to start entering the mantissa part it does nothing, but it is supposed to change the position and jump after the dot/comma. 

It works on the iOS simulator and Android emulator if dots are entered. 

But doesn't work on real devices(videos attached). On iPhone 13 `TextInputType.numberWithOptions(decimal: true)` opens the keyboard only with a comma, so it will be cool if the comma support will appear in the package.

`iPhone 12 mini, iOS 15.6.1`
https://drive.google.com/file/d/12d-pdf6jyGrO7AvpLiKKqsvFdFH-oQZa/view?usp=sharing

`Samsung Galaxy S8, Android 9`
https://drive.google.com/file/d/1O4nlT6ECYIGVW4naf7CZlwFk5jzLMiIf/view?usp=sharing

**Comment by caseyryan** [comment]
Hi!
Two questions
1) What is the language locale on your device? It affects the input type
2) Can you provide a complete code snippet that reproduces the bug?

**Comment by jackie-maxx** [comment]
> Hi! Two questions
> 
> 1. What is the language locale on your device? It affects the input type
> 2. Can you provide a complete code snippet that reproduces the bug?

i have this problem too. 
1.locale : cambodia
2. in the TextFormField 
inputFormatters: [
                            CurrencyInputFormatter(
                              thousandSeparator: ThousandSeparator.Comma,
                              mantissaLength: 2,
                            ),
                          ],
