### ISSUE TITLE
CreditCardNumberInputFormatter not working at all

### ISSUE THREAD

**Issue by alejandrogiubel** [caseyryan/flutter_multi_formatter#99]
CreditCardNumberInputFormatter not working at all. I am using the provided example and not work at all.
<img width="449" alt="Captura de Pantalla 2022-10-06 a la(s) 9 24 00 p m" src="https://user-images.githubusercontent.com/36578847/194446636-cfc48155-5c60-4ecc-ae65-838d655d203c.png">

```
return TextFormField(
      decoration: InputDecoration(
        border: const OutlineInputBorder(),
        hintText: 'CARD NUMBER',
        hintStyle: TextStyle(
          color: Colors.black.withOpacity(.3),
        ),
        errorStyle: const TextStyle(
          color: Colors.red,
        ),
      ),
      keyboardType: TextInputType.number,
      inputFormatters: [
        CreditCardNumberInputFormatter(
          onCardSystemSelected: (CardSystemData? cardSystemData) {
            print(cardSystemData);
          },
        ),
      ],
    );
```

**Comment by caseyryan** [comment]
It works fine. Check your code, you're definitely doing something wrong

**Comment by alejandrogiubel** [comment]
You're right. I thought it also validates the number of digits regardless of the type of card.
